name: dev_iqm
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2
  - ca-certificates
  - expat
  - libcxx
  - libffi
  - ncurses
  - openssl
  - pip
  - python=3.12.3
  - readline
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib
  - pip:
      - annexremote==1.6.5
      - argcomplete==3.3.0
      - beautifulsoup4==4.12.3
      - boto3==1.34.124
      - botocore==1.34.124
      - certifi==2024.6.2
      - cffi==1.16.0
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - citeproc-py==0.6.0
      - coverage==7.5.3
      - cryptography==42.0.8
      - datalad==1.1.0
      - distro==1.9.0
      - duecredit==0.10.2
      - fasteners==0.19
      - filelock==3.15.1
      - fsspec==2024.6.0
      - httpretty==1.1.4
      - humanize==4.9.0
      - idna==3.7
      - image-similarity-measures==0.3.6
      - imageio==2.35.1
      - iniconfig==2.0.0
      - iso8601==2.1.0
      - jaraco-classes==3.4.0
      - jaraco-context==5.3.0
      - jaraco-functools==4.0.1
      - jeepney==0.8.0
      - jinja2==3.1.4
      - jmespath==1.0.1
      - keyring==25.2.1
      - keyrings-alt==5.0.1
      - lazy-loader==0.4
      - looseversion==1.3.0
      - lpips==0.1.4
      - lxml==5.2.2
      - markupsafe==2.1.5
      - more-itertools==10.3.0
      - mpmath==1.3.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - mypy==1.10.0
      - mypy-extensions==1.0.0
      - networkx==3.3
      - nibabel==5.2.1
      - numpy==1.26.4
      - opencv-python==4.10.0.84
      - packaging==24.1
      - pandas==2.2.2
      - patool==2.2.0
      - phasepack==1.5
      - pillow==10.3.0
      - piq==0.8.0
      - platformdirs==4.2.2
      - pluggy==1.5.0
      - pycparser==2.22
      - pyperclip==1.8.2
      - pytest==8.2.2
      - pytest-cov==5.0.0
      - pytest-fail-slow==0.6.0
      - python-dateutil==2.9.0.post0
      - python-gitlab==4.6.0
      - pytz==2024.1
      - pywavelets==1.6.0
      - pyyaml==6.0.1
      - requests==2.32.3
      - requests-ftp==0.3.1
      - requests-toolbelt==1.0.0
      - s3transfer==0.10.1
      - scikit-image==0.20.0
      - scipy==1.13.1
      - secretstorage==3.3.3
      - six==1.16.0
      - soupsieve==2.5
      - sympy==1.12.1
      - tifffile==2024.5.22
      - torch==2.3.1
      - torchvision==0.18.1
      - tqdm==4.66.4
      - types-python-dateutil==2.9.0.20240316
      - types-requests==2.32.0.20240602
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.1
      - v==1
      - vcrpy==6.0.1
      - wrapt==1.16.0
      - yarl==1.9.4
