data:
  folder: "/home/iml/hannah.eichhorn/Data/IQM/openneuro_dataset/ds004332/"
  subjects: ["sub-01"]
output:
  metrics: ["FSIM", "Tenengrad", "NGS", "GradientEntropy", "VIF", "PerceptualMetric"]
  reduction: "worst"   # or "mean"
